# This is Makefile for ESP32 IDF

COMPONENT_ADD_INCLUDEDIRS := .
COMPONENT_SRCDIRS := .

ifdef CONFIG_ESP32_BOARD_NNC2019
COMPONENT_ADD_INCLUDEDIRS += ./NNC2019
COMPONENT_SRCDIRS += ./NNC2019
endif

ifdef CONFIG_ESP32_BOARD_M5STICKC
COMPONENT_ADD_INCLUDEDIRS += ./M5STICKC
COMPONENT_SRCDIRS += ./M5STICKC
endif

ifdef CONFIG_ESP32_BOARD_TTGO
COMPONENT_ADD_INCLUDEDIRS += ./TTGO
COMPONENT_SRCDIRS += ./TTGO
endif


