# This is Makefile for ESP32 IDF

COMPONENT_ADD_INCLUDEDIRS := .
COMPONENT_SRCDIRS := .

ifdef CONFIG_ESP32_BOARD_NNC2019
COMPONENT_ADD_INCLUDEDIRS += ./nnc2019
COMPONENT_SRCDIRS += ./nnc2019
endif

ifdef CONFIG_ESP32_BOARD_M5STICKC
COMPONENT_ADD_INCLUDEDIRS += ./m5stickc
COMPONENT_SRCDIRS += ./m5stickc
endif

ifdef CONFIG_ESP32_BOARD_TTGO
COMPONENT_ADD_INCLUDEDIRS += ./TTGO
COMPONENT_SRCDIRS += ./TTGO
endif


